globalMode: "deny"
globalProvider: "open-registry"
globalRegistries: 
  - "index.docker.io/betorvs"
globalAllowedImages:
  - "public.ecr.aws/docker/library/redis:8.2.3-alpine"
globalPublicKey: |
  -----BEGIN PUBLIC KEY-----
  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEXBC/tG86ZkNXCMSODNnqWSv94czb
  QwYxG2qpcX90HRs3amRFfKMFcKWDNf3AmFmGRVySxvZYZ6ZR7WqYRTMm5Q==
  -----END PUBLIC KEY-----

policies:
  - name: "Google Artifact Registry - Production"
    pattern: "gcr.io/my-company/*"
    provider: "google"
    registries:
     - "gcr.io/my-company"
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE... (GCP Specific Key)
      -----END PUBLIC KEY-----
    mode: "deny"

  - name: "AWS ECR"
    pattern: "123456789123.dkr.ecr.us-east-1.amazonaws.com/*"
    provider: "aws"
    registries: 
     - "123456789123.dkr.ecr.us-east-1.amazonaws.com"
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE... (AWS KMS public key here)
      -----END PUBLIC KEY-----
    mode: "deny"

  - name: "DockerHub Public Tools"
    pattern: "docker.io/library/*"
    publicKey: "/etc/dvorah/keys/docker-sig.pub" # path or string literal
    provider: "open-registry"
    mode: "audit" # allow public images but with warning

  - name: "keyless example"
    pattern: "ghcr.io/betorvs/dvorah:*"
    provider: "open-registry"
    registries:
      - "ghcr.io/betorvs/dvorah"
    mode: "deny"
    identity_regex: "^https://github.com/betorvs/dvorah/.github/workflows/release.yaml@refs/(heads/main|tags/v.*)$"
    issuer: "https://token.actions.githubusercontent.com"

  - name: "cert manager"
    pattern: "quay.io/jetstack/cert-manager*"
    provider: "open-registry"
    registries:
      - "quay.io/jetstack"
    mode: "deny"
    publicKeyHash: sha512
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsZZKaaIRjOpzbiWYIDKO
      yry9XGBqAfve1iOGmt5VO1jpjNoEseT6zewozHfWTM7osxayy2WjN8G+QV39MlT3
      Vxo91/31g+Zcq8KcvxG+iB8GRaD9pNgLmghorv+eYDiPYMO/+fhsLImyG5WEoPct
      MeCBD7umZ/A2t96U9DQxVDqQbTHlsNludno1p1wsgRnfUM3QHexNljDvJg5FcDMo
      dCpVLpRNvbw0lbJVfybJ4siJ5o/MmXzy0QCJpw+yMIqvqMc8qgKJ1yooJtuTVF4t
      4/luP+EG/oVIiSWCFeRMqYdbJ3R+CJi+4LN7vFNYQM1Q/NwOB52RteaR7wnqmcBz
      qSYK32MM8xdPCQ5tioWwnPTRbPZuzsZsRmJsKBO9JUrBYdDntZX1xY5g4QNSufxi
      QgJgJSU7E4VGMvagEzB1JzvOr6A/qNFCO1Z6JsA3jw3cJLV1rSHfxqfSXBACTLDf
      6bOPWRILRKydTJA6uLKNKmo1/nFm3jvd5tHKOjy4VAQLJ/Vx9wBsAAiLa+06veun
      Oz3AJ9sNh3wLp21RL11u9TuOKRBipE/TYsBYp8jpIyWPXDSV+JcD/TZqoT8y0Z6S
      0damfUmspuK9DTQFL2crpeaqJSG9RA+OuPZLxGD1IMURTsPJB7kXhPtmceeirBnw
      sVcRHHDitVt8oO/x4Wus1c0CAwEAAQ==
      -----END PUBLIC KEY-----