apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dvorah.fullname" . }}
  labels:
    {{- include "dvorah.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dvorah.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dvorah.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dvorah.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -cert={{.Values.args.cert}}
            - -key={{.Values.args.key}}
            - -port={{ .Values.service.port }}
            - -adm-port={{ .Values.service.metrics.port }}
            - -log-level={{.Values.args.logLevel}}
            - -digest-cache-size={{.Values.args.digestCacheSize}}
            - -digest-cache-ttl={{.Values.args.digestCacheTTL}}
            - -tag-cache-size={{.Values.args.tagCacheSize}}
            - -tag-cache-ttl={{.Values.args.tagCacheTTL}}
            - -owner-cache-size={{.Values.args.ownerCacheSize}}
            - -owner-cache-ttl={{.Values.args.ownerCacheTTL}}
            - -use-tag-cache={{.Values.args.useTagCache}}
            {{- if not .Values.args.policyConfig }}
            - -mode={{.Values.args.mode}}
            - -public-key={{.Values.args.publicKey}}
            - -registry={{.Values.args.registry}}
            {{- end }}
            {{- if .Values.args.policyConfig }}
            - -policy-config=/config/config.yaml
            {{- end }}
            {{- if .Values.args.skipDvorahValidation }}
            - -dvorah-validation=false
            {{- end }}
          {{- if .Values.env.enabled }}
          env:
            - name: DVORAH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- with .Values.env.content }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.service.metrics.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: dvorah-certs
              mountPath: "/etc/dvorah/certs"
              readOnly: true
            - mountPath: /.docker/config.json
              name: dvorah-config-volume
              subPath: config.json
            {{- if not .Values.args.policyConfig }}
            - mountPath: /cosign/cosign.pub
              name: dvorah-config-volume
              subPath: cosign.pub
            {{- end}}
            {{- if .Values.args.policyConfig }}
            - mountPath: /config/config.yaml
              name: dvorah-config-volume
              subPath: config.yaml
            {{- end}}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: dvorah-certs
          secret:
            secretName: dvorah-certificates
        - name: dvorah-config-volume
          configMap:
            name: dvorah-config
            items:
            - key: docker-config.json
              path: docker-config.json
            {{- if not .Values.args.policyConfig }}
            - key: cosign.pub
              path: cosign.pub
            {{- end}}
            {{- if .Values.args.policyConfig }}
            - key: config.yaml
              path: config.yaml
            {{- end}}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
