---
name: pr
on:
  pull_request:
    branches:
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417  # v6.3.0
        with:
          go-version: '1.26.1'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20  # v9.2.0
        with:
          version: v2.11
          args: --timeout=10m
      - name: Run Gosec Security Scanner
        uses: securego/gosec@223e19b8856e00f02cc67804499a83f77e208f3c # v2.25.0
        with:
          args: ./...
  e2e-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # install Task
      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611  # v2.0.0
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417  # v6.3.0
        with:
          go-version: '1.26'
          cache: false
      - name: tidy
        run: |
          task tidy
      - name: e2e-unit-tests
        run: |
          task dvorah-e2e-test

  build-image:
    needs: [golangci, "e2e-test"]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write 

    name: build-image
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Install Cosign
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
        with:
          driver-opts: |
            image=moby/buildkit:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=long,prefix=
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/ci-pipeline' }}
          labels: |
            org.opencontainers.image.description=Dvorah: A Zero Trust Kubernetes Admission Controller for Cosign signatures.
            org.opencontainers.image.verify-command=cosign verify ghcr.io/${{ github.repository }}:TAG --certificate-identity-regexp="^https://github.com/${{ github.repository }}/.github/workflows/pr.yaml@refs/pull/.*/merge$" --certificate-oidc-issuer=https://token.actions.githubusercontent.com
          annotations: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=Dvorah - a Kubernetes Admission Controller for image signature verification. 

      - name: Build and Push container images
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        id: build-and-push
        with:
          context: .
          file: ./Dockerfiles/dvorah/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          annotations: ${{ steps.docker_meta.outputs.annotations }}
          provenance: mode=max
          sbom: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign and verify the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ${{ steps.docker_meta.outputs.tags }}
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository }}"
          cosign sign --yes "${IMAGE_NAME}@${DIGEST}"
          
          cosign verify "${IMAGE_NAME}@${DIGEST}" \
          --certificate-identity-regexp="^https://github.com/${{ github.repository }}/.github/workflows/pr.yaml@refs/pull/.*/merge$" \
          --certificate-oidc-issuer=https://token.actions.githubusercontent.com